# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af61400b7982e7387d4c26e9cdbe0919bec057a5e91a06ac8c7aa4ab95ef63870b6ebc6a7a13ad47fb1cf70e0eadc3025227adab67f224cb0cfd3f2fe57baff7

test:
  secret_key_base: bd49c24d8689c9eaeebbcc96357b9fe528d1a54982b57076ad583e12b6d98351e939d7cd0fc96d5345d806ab426a520ecd6975915afc77746b5fcaf21e4d6ed2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
